# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='second_address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
